default:
  http_metas:
    content-type: text/html; charset = utf-8

  metas:
    title:        I存钱WEB管理系统-Expacta
    robots:       index, follow
    description:  I存钱WEB管理系统-Expacta
    keywords:     I存钱WEB管理系统-Expacta
    language:     zh

  stylesheets:    [main]

  javascripts:    [jquery-1.9.1.min.js, jquery.cookie.js, main.js, jQuery.select.js]

  has_layout:     on
  layout:         layout
