default:
  http_metas:
    content-type: text/html

  metas:
    title:        Expacta  Manager
    robots:       index, follow
    description:  Expacta  Manager
    keywords:     Expacta  Manager
    language:     en

  stylesheets:
    - main.css
    - style.css
    - dtree.css
    - jquery/jquery-ui-1.8.16.custom.css
    - menuCSS.css

  javascripts:
    - dtree.js
    - uat2.js
    - jquery-1.7.1.min.js
    - jquery-ui-1.8.16.custom.min.js
    - yui/build/utilities/utilities.js
    - yui/build/yahoo/yahoo-min.js
    - yui/build/event/event-min.js
    - yui/build/dom/dom-min.js
    - yui/build/element/element-beta-min.js
    - yui/build/button/button-min.js
    - yui/build/container/container-min.js
    - yui/build/tabview/tabview-min.js

  has_layout:     on
  layout:         layout
