default:
  http_metas:
    content-type: ''

  metas:
    title:        API -  iCunQian
    robots:       index, follow
    description:   API -  iCunQian
    keywords:      API -  iCunQian
    language:     zh

  stylesheets:    []

  javascripts:    []

  has_layout:     off
  layout:         layout
