indexSuccess:
  metas: { title: 理财产品 - i存钱}

editSuccess:
  metas: { title: 添加/修改理财产品 - i存钱}

importSuccess: 
  metas: { title: Excel批量导入 - i存钱}

recommendSuccess:
  javascripts: [jquery.jqEasyCharCounter.min.js]
  metas: { title: 消息推送服务 - i存钱}