default:
  http_metas:
    content-type: text/html

  metas:
    title:        i存钱
    robots:       index, follow
    description:  i存钱
    keywords:     i存钱
    language:     zh

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
