all:
  propel:
    class:          sfPropelDatabase
    param:
      #dsn:          mysql://deposit_devel:deposit_devel123@localhost/deposit_devel
      dsn:          mysql://root:root@localhost/deposit_test
      encoding:     utf8