propel:
  _attributes:      { package: lib.model }
  deposit_region:
    id:                                                   ~
    parent_id:                                            { type: integer, required: true, default: 0 }
    name:                                                 { type: varchar(45), required: true, default: '' }
    created_at:                                           ~
    updated_at:                                           ~
    _indexes:
      parent_id:                                          [  ]
      name:                                               [  ]
      created_at:                                         [  ]  
      updated_at:                                         [  ]
  deposit_bank:
    id:                                                   ~
    name:                                                 { type: varchar(100), required: true, default: '' }
    short_name:                                           { type: varchar(64), required: true, default: '' }
    short_char:                                           { type: varchar(16), required: true, default: '' }
    phone:                                                { type: varchar(32), required: true, default: '' }
    logo:                                                 { type: varchar(64), required: true, default: '' }
    is_valid:                                             { type: tinyint, required: true, default: 0 }
    sync_status:                                          { type: tinyint, required: true, default: 0 }
    created_at:                                           ~
    updated_at:                                           ~
    _indexes:
      name:                                               [  ]
      short_name:                                         [  ]
      short_char:                                         [  ]
      phone:                                              [  ]
      logo:                                               [  ]
      is_valid:                                           [  ]
      sync_status:                                        [  ]
      created_at:                                         [  ]
      updated_at:                                         [  ]
  deposit_bank_alias:
    id:                                                   ~
    deposit_bank_id:                                      { type: integer, required: true, foreignTable: deposit_bank, foreignReference: id }
    name:                                                 { type: varchar(255), required: true, default: '' }
    created_at:                                           ~
    updated_at:                                           ~
    _indexes:
      fk_deposit_bank_alias_deposit_bank:                 [ deposit_bank_id ]
      name:                                               [  ]
      created_at:                                         [  ]
      updated_at:                                         [  ]
    _uniques:
      uk_bank_alias:                                      [ deposit_bank_id, name ]
  deposit_financial_products:
    id:                                                   ~
    name:                                                 { type: varchar(255), required: true, default: '' }
    bank_name:                                            { type: varchar(255), required: true, default: '' }
    bank_id:                                              { type: integer, required: true, default: 0 }
    region:                                               { type: varchar(255), required: true, default: '' }
    profit_type:                                          { type: varchar(48), required: true, default: '' }
    currency:                                             { type: varchar(32), required: true, default: '' }
    invest_cycle:                                         { type: float, required: true }
    target:                                               { type: varchar(128), required: true, default: '' }
    sale_start_date:                                      { type: date, required: true }
    sale_end_date:                                        { type: date, required: true }
    profit_start_date:                                    { type: date, required: true }
    deadline:                                             { type: date, required: true }
    pay_period:                                           { type: varchar(45), required: true, default: '' }
    expected_rate:                                        { type: float, required: true }
    actual_rate:                                          { type: float, required: true }
    invest_start_amount:                                  { type: varchar(32), required: true, default: '' }
    invest_increase_amount:                               { type: varchar(32), required: true, default: '' }
    profit_desc:                                          longvarchar
    invest_scope:                                         longvarchar
    stop_condition:                                       longvarchar
    raise_condition:                                      longvarchar
    purchase:                                             longvarchar
    cost:                                                 longvarchar
    feature:                                              longvarchar
    events:                                               longvarchar
    warnings:                                             longvarchar
    announce:                                             longvarchar
    status:                                               { type: varchar(32), required: true, default: '' }
    sync_status:                                          { type: tinyint, required: true, default: 0 }
    created_at:                                           ~
    updated_at:                                           ~
    _indexes:
      name:                                               [  ]    
      bank_name:                                          [  ]
      bank_id:                                            [  ]
      region:                                             [  ]
      profit_type:                                        [  ]                  
      currency:                                           [  ]  
      target:                                             [  ]
      sale_start_date:                                    [  ]      
      sale_end_date:                                      [  ]
      profit_start_date:                                  [  ]
      deadline:                                           [  ]    
      pay_period:                                         [  ]
      expected_rate:                                      [  ]
      actual_rate:                                        [  ]
      invest_start_amount:                                [  ]   
      invest_increase_amount:                             [  ]   
      created_at:                                         [  ]
      updated_at:                                         [  ]
      status:                                             [  ]
      sync_status:                                        [  ]
    _uniques:
      uk_financial_products:                              [ name(120), profit_type, currency, invest_cycle, sale_start_date, sale_end_date, profit_start_date, deadline, pay_period, expected_rate, actual_rate, invest_start_amount, invest_increase_amount ]
  deposit_personal_products:
    id:                                                  ~
    deposit_financial_products_id:                       { type: integer, required: true, primaryKey: true, foreignTable: deposit_financial_products, foreignReference: id }  
    deposit_members_id:                                  { type: integer, required: true, primaryKey: true, foreignTable: deposit_members, foreignReference: id }
    expected_rate:                                       { type: float, required: true }
    amount:                                              { type: float, required: true }
    buy_date:                                            { type: timestamp, sqltype: datetime, required: true}
    expiry_date:                                         { type: timestamp, sqltype: datetime, required: true}
    is_valid:                                            { type: varchar, sqltype: enum, size: "'yes','no'",  default: 'no', required: true}
    created_at:                                          ~
    updated_at:                                          ~
    _indexes:
      fk_deposit_personal_products_deposit_financial_products1:       [ deposit_financial_products_id ]
      fk_deposit_personal_products_deposit_members:                   [ deposit_members_id ]
      expected_rate:                                                  [  ]
      amount:                                                         [  ]
      buy_date:                                                       [  ]
      expiry_date:                                                    [  ]
      is_valid:                                                       [  ]
      created_at:                                                     [  ]
      updated_at:                                                     [  ]
  deposit_attributes:
    id:                                                   ~
    parent_id:                                            { type: integer, required: true, default: 0 }
    type:                                                 { type: varchar(32), required: true, default: '' }
    value:                                                { type: varchar(128), required: true, default: '' }
    sync_status:                                          { type: tinyint, required: true, default: 0 }
    created_at:                                           ~
    updated_at:                                           ~
    _indexes:
      parent_id:                                          [  ]
      type:                                               [  ]
      value:                                              [  ]
      sync_status:                                        [  ]
      created_at:                                         [  ]
      updated_at:                                         [  ]
