propel:
  _attributes:      { package: lib.model }
  deposit_members:
    id:                                   ~
    account:                              { type: varchar(45), required: true, default: '' }
    nickname:                             { type: varchar(45), required: true, default: '' }
    password:                             { type: varchar(45), required: true, default: '' }
    mobile:                               { type: varchar(12), required: true, default: '' }
    email:                                { type: varchar(100), required: true, default: '' }
    avatar:                               { type: varchar(100), required: true, default: '' }
    mobile_active:                        { type: varchar, sqltype: enum, size: "'yes','no'", default: 'no', required: true}
    email_active:                         { type: varchar, sqltype: enum, size: "'yes','no'", default: 'no', required: true}
    #third_party_platform_type:            { type: enum, required: true, default: '' }
    third_party_platform_type:            { type: varchar, sqltype: enum, size: "'qq','tencert_weibo','weibo', 'weixin', 'null'", default: 'null', required: true}
    third_party_platform_account:         { type: varchar(45), required: true, default: '' }
    #registration_time:                    { type: datetime, required: true }
    registration_time:                    { type: timestamp, sqltype: datetime, required: true}
    is_login:                             { type: varchar, sqltype: enum, size: "'yes','no'",  default: 'no', required: true}
    #last_login:                           { type: datetime, required: true }
    last_login:                           { type: timestamp, sqltype: datetime, required: true}
    hash:                                 { type: varchar(45), required: true, default: ''}
    registration_complete:                { type: varchar, sqltype: enum, size: "'0', '1', '2', '3'", default: '0', required: true }
    chinese:                              { type: varchar(45), required: true, default: '' }
    created_at:                           ~
    updated_at:                           ~
    _indexes:
      account:                            [  ]
      nickname:                           [  ]
      password:                           [  ]
      mobile:                             [  ]
      email:                              [  ]
      avatar:                             [  ]
      mobile_active:                      [  ]
      email_active:                       [  ]
      third_party_platform_type:          [  ]
      third_party_platform_account:       [  ]
      registration_time:                  [  ]
      last_login:                         [  ]
      hash:                               [  ]
      registration_complete:              [  ]
      chinese:                            [  ]
      created_at:                         [  ]
      updated_at:                         [  ]
    _uniques:
      uk_account:                         [ account, nickname, mobile, email ]
  deposit_notification:
    id:                                   ~
    #notification_type:                    { type: enum, required: true, default: '' }
    notification_type:                    { type: 'varchar', sqltype: enum, size: "'email','sms'", default: 'sms', required: true}
    notification_type_account:            { type: varchar(45), required: true, default: '' }
    content:                              { type: varchar(255), required: true, default: '' }
    #notification_status:                  { type: enum, required: true, default: '' }
    notification_status:                  { type: 'varchar', sqltype: enum, size: "'queued','delivered','failed'", default: 'queued', required: true}
    #delivered_time:                       { type: datetime, required: true }
    delivered_time:                       { type: timestamp, sqltype: datetime, required: true}  
    error_message:                        { type: varchar(255), required: true, default: '' }
    created_at:                           ~
    updated_at:                           ~
    _indexes:
      notification_type:                  [  ]
      notification_type_account:          [  ]
      content:                            [  ]
      notification_status:                [  ]
      delivered_time:                     [  ]
      error_message:                      [  ]
      created_at:                         [  ]
      updated_at:                         [  ]

  deposit_feedback:
    id:                                          ~
    deposit_members_id:                          { type: integer, required: true, foreignTable: deposit_members, foreignReference: id }
    email:                                       { type: varchar(100), required: true, default: '' }
    content:                                     { type: varchar(255), required: true, default: '' }
    mail_send_status:                            {type: varchar, sqltype: enum, size: "'yes', 'no'", default: 'no', required: true}
    #mail_send_status:                            { type: enum, required: true, default: no }
    created_at:                                  ~
    updated_at:                                  ~
    _indexes:
      fk_deposit_feedback_deposit_members:       [ deposit_members_id ]
      email:                                     [  ]
      content:                                   [  ]
      mail_send_status:                          [  ]
      created_at:                                [  ]
      updated_at:                                [  ]
  deposit_members_favorites:
    id:                                                               ~
    deposit_members_id:                                               { type: integer, required: true, primaryKey: true, foreignTable: deposit_members, foreignReference: id }
    deposit_financial_products_id:                                    { type: integer, required: true, primaryKey: true, foreignTable: deposit_financial_products, foreignReference: id }
    sync_status:                                                      { type: varchar, sqltype: enum, size: "'0', '1', '2'", default: '0', required: true }
    uuid:                                                             { type: varchar(45), required: true, default: '' }
    created_at:                                                       ~
    updated_at:                                                       ~
    _indexes:
      fk_deposit_member_favorites_deposit_members1:                   [ deposit_members_id ]
      fk_deposit_member_favorites_deposit_financial_products1:        [ deposit_financial_products_id ]
      sync_status:                                                    [  ]
      uuid:                                                           [  ]
      created_at:                                                     [  ]
      updated_at:                                                     [  ]
  depost_members_settings:
    id:                                                               ~
    deposit_members_id:                                               { type: integer, required: true, foreignTable: deposit_members, foreignReference: id }
    #deadline_reminder:                                                { type: enum, required: true, default: no }
    deadline_reminder:                                                { type: varchar, sqltype: enum, size: "'yes', 'no'", default: 'no', required: true}
    created_at:                                                       ~
    updated_at:                                                       ~
    _indexes:
      fk_depost_member_settings_deposit_members1:                     [ deposit_members_id ]
      deadline_reminder:                                              [  ]
      created_at:                                                     [  ]
      updated_at:                                                     [  ]
  deposit_members_token:
    id:                                                               ~
    deposit_members_id:                                               { type: integer, required: true, primaryKey: true, foreignTable: deposit_members, foreignReference: id }
    push_devices_id:                                                  { type: integer, required: true, primaryKey: true, foreignTable: push_devices, foreignReference: id }
    is_valid:                                                         { type: varchar, sqltype: enum, size: "'yes', 'no'", default: 'no', required: true}
    created_at:                                                       ~
    updated_at:                                                       ~
    _indexes:
      fk_deposit_members_token_deposit_members1:                      [ deposit_members_id ]
      fk_deposit_members_token_push_devices1:                         [ push_devices_id ]
      created_at:                                                     [  ]
      updated_at:                                                     [  ]
      is_valid:                                                       [  ]
  deposit_members_subscribe:
    id:                                                               ~
    deposit_members_id:                                               { type: integer, required: true, primaryKey: true, foreignTable: deposit_members, foreignReference: id }
    deposit_bank_id:                                                  { type: integer, required: true, primaryKey: true, foreignTable: deposit_bank, foreignReference: id }
    city:                                                             { type: varchar(255), required: true, default: '' }
    profit_type:                                                      { type: varchar(45), required: true, default: '' }
    expected_rate:                                                    { type: decimal, required: true }
    invest_cycle:                                                     { type: float, required: true }
    is_valid:                                                         { type: varchar, sqltype: enum, size: "'yes', 'no'", default: 'no', required: true}
    created_at:                                                       ~
    updated_at:                                                       ~
    _indexes:
      fk_deposit_members_subscribe_deposit_bank1:                     [ deposit_bank_id ]
      city:                                                           [  ]
      profit_type:                                                    [  ]
      expected_rate:                                                  [  ]
      invest_cycle:                                                   [  ]
      created_at:                                                     [  ]
      updated_at:                                                     [  ]
      fk_deposit_members_subscribe_deposit_members1:                  [ deposit_members_id ]
      is_valid:                                                       [  ]
  deposit_station_news:
    id:                                                               ~
    title:                                                            { type: varchar(255), required: true, default: '' }
    content:                                                          { type: longvarchar, required: true, default: '' }
    send_time:                                                        { type: timestamp, sqltype: datetime, required: true }
    type:                                                             { type: varchar(16), required: true, default: 'default' }
    deposit_financial_products_id:                                    { type: integer, required: true, default: 0 }
    created_at:                                                       ~
    updated_at:                                                       ~
    _indexes:
      type:                                                           [  ]
      deposit_financial_products_id:                                  [  ]
      send_time:                                                      [  ]
      created_at:                                                     [  ]
      updated_at:                                                     [  ]
    _uniques:
      unique:                                                         [ title(100), content(100), send_time, type ]
  deposit_members_station_news:
    id:                                                               ~
    deposit_station_news_id:                                          { type: integer, required: true, primaryKey: true, foreignTable: deposit_station_news, foreignReference: id }
    deposit_members_id:                                               { type: integer, required: true, primaryKey: true, foreignTable: deposit_members, foreignReference: id }
    status:                                                           { type: varchar, sqltype: enum, size: "'0', '1', '2'", default: '0', required: true}
    created_at:                                                       ~
    updated_at:                                                       ~
    _indexes:
      fk_deposit_members_station_news_deposit_station_news1:          [ deposit_station_news_id ]
      fk_deposit_members_station_news_deposit_members1:               [ deposit_members_id ]
      status:                                                         [  ]
      created_at:                                                     [  ]
      updated_at:                                                     [  ]