propel:
  _attributes:      { package: lib.model }
  push_devices:
    id:                                    ~
    client_id:                             { type: varchar(128), required: true, default: '' }
    app_name:                              { type: varchar(255), required: true, default: '' }
    app_version:                           { type: varchar(45), required: true, default: '' }
    device_uid:                            { type: varchar(255), required: true, default: '' }
    device_name:                           { type: varchar(255), required: true, default: '' }
    device_model:                          { type: varchar(100), required: true, default: '' }
    device_version:                        { type: varchar(45), required: true, default: '' }
    device_token:                          { type: varchar(255), required: true, default: '' }
    # development:                           { type: enum, required: true, default: 'sandbox' }
    # status:                                { type: enum, required: true, default: 'active' }
    development:                           { type: 'varchar', sqltype: enum, size: "'production', 'sandbox'", default: 'sandbox', required: true}
    status:                                { type: 'varchar', sqltype: enum, size: "'active', 'unregistered'", required: ture, default: 'unregistered'}
    created_at:                            ~
    updated_at:                            ~
    _indexes:
      client_id:                           [  ]
      app_name:                            [  ]
      app_version:                         [  ]
      device_uid:                          [  ]
      device_name:                         [  ]
      device_model:                        [  ]
      device_version:                      [  ]
      device_token:                        [  ]
      development:                         [  ]
      status:                              [  ]
      created_at:                          [  ]
      updated_at:                          [  ]
    _uniques:
      unique_appname_uid:                  [ app_name, device_uid ]
      unique_appname_token:                [ app_name, device_token ]
  push_messages:
    id:                                    ~
    deposit_members_id:                                               { type: integer, required: true, primaryKey: true, foreignTable: deposit_members, foreignReference: id }
    deposit_financial_products_id:                                    { type: integer, required: true, primaryKey: true, foreignTable: deposit_financial_products, foreignReference: id }
    message:                               { type: varchar(255), required: true, default: '' }
    # delivery:                              { type: datetime, required: true }
    delivery:                              { type: timestamp, sqltype: datetime, required: true}
    # status:                                { type: enum, required: true, default: 'queued' }
    status:                                { type: 'varchar', sqltype: enum, size: "'queued', 'delivered', 'failed'", default: "queued", required: true }
    error_message:                         { type: varchar(255), required: true, default: '' }
    created_at:                            ~
    updated_at:                            ~
    _indexes:
      fk_push_messages_push_devices:       [ push_devices_id ]
      message:                             [  ]
      delivery:                            [  ]
      status:                              [  ]
      error_message:                       [  ]
      created_at:                          [  ]
      updated_at:                          [  ]
      fk_push_messages_deposit_members1:                              [ deposit_members_id ]
      fk_push_messages_deposit_financial_products1:                   [ deposit_financial_products_id ]
  push_message_template:
    id:                                    ~
    content:                               { type: longvarchar, required: true, default: '' }
    type:                                  { type: tinyint, required: true, default: 0 }
    created_at:                            ~
    updated_at:                            ~
    _indexes:
      content:                             [  ]
      type:                                [  ]
      created_at:                          [  ]
      updated_at:                          [  ]
