propel:
  _attributes:
    package: lib.model
  api_login_information:
    id:                                                 { type: integer, required: true, primaryKey: true, autoIncrement: true }
    code:                                               { type: varchar, size: 255 }
    api_key:                                            { type: char, size: 40 }
    token:                                              { type: char, size: 40 }
    request_ip:                                         { type: char, size: 15 }
    created_at:                                         ~
    updated_at:                                         ~
    _indexes:
      code:                                             [ code ]
      token:                                            [ token ]
